### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Ablott123** [DIY-Z/SLADD-Learning#2]
is:issue is:open 您好，可以分享你的数据集吗？我的在官网上用代码下载不下来，非常感谢！我的邮箱是1715547342@qq.com

**Comment by DIY-Z** [comment]
你可以从这个github仓库提供的下载链接里下载：https://github.com/SCLBD/DeepfakeBench#2-download-data

**Comment by Ablott123** [comment]
谢谢~~

**Comment by Ablott123** [comment]
谢谢啦~~真好


czy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DIY-Z/SLADD-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月2日(星期四) 晚上8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DIY-Z/SLADD-Learning] 数据集 (Issue #2)





 
你可以从这个github仓库提供的下载链接里下载：https://github.com/SCLBD/DeepfakeBench#2-download-data
